#' @title Adds Outliers
#' @param data data.frame.
#' @param p Proportion of outliers to add to data.
#' @param sd_factor Each outlier is generated by shifting the original value by a
#'   realization of a normal random variable with `sd_factor` times
#'   the original sample standard deviation.
#' @param seed An integer seed.
#' @returns data with some outliers.
#' @export
#' @examples
#' generateOutliers(iris, p = 0.5, sd_factor = 5, seed = 123)
generateOutliers <- function(data, p = 0.5, sd_factor = 5, seed = NULL){
    if (p <= 0 || p > 1|| sd_factor <= 0) {
        stop("p and sd_factor must be between 0 and 1")
    }
    if (is.null(seed)) {
    set.seed(123)
    } else {
    set.seed(seed)
    }
    numeric_features <- names(data)[sapply(data,is.numeric)]
    for (features in numeric_features){
        n <- length(data[,features])
        m <- round(p * n)
        data[sample(n,m),features] <- round(data[m,features] + sd_factor  * sample(c(-1, 1), m, replace = TRUE) * rnorm(m,sd(data[[features]])),2)
    }
    return(data)
}
